# Generated by Django 4.2.10 on 2024-03-13 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('admin_user_id', models.CharField(max_length=100)),
                ('admin_user_name', models.CharField(default='NA', max_length=100)),
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('group_members', models.JSONField()),
                ('visibility_type', models.CharField(max_length=20)),
                ('description', models.CharField(default='NA', max_length=250)),
                ('group_name', models.CharField(default='untitled', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('labels', models.CharField(blank=True, max_length=100, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='task_attachments/')),
                ('group_id', models.CharField(max_length=100)),
                ('assigned_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
