# Generated by Django 4.2.10 on 2024-03-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('admin_user_id', models.CharField(max_length=100)),
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('group_members', models.JSONField()),
                ('visibility_type', models.CharField(max_length=20)),
                ('description', models.CharField(default='NA', max_length=250)),
                ('group_name', models.CharField(default='untitled', max_length=100)),
            ],
        ),
    ]
