# Generated by Django 4.2.10 on 2024-03-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin_user_username',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
