# Generated by Django 4.2.10 on 2024-03-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_group_admin_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='admin_user_username',
            new_name='admin_user_name',
        ),
    ]
