# Generated by Django 4.2.10 on 2024-03-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='not-started', max_length=20),
        ),
    ]
