# Generated by Django 4.2.10 on 2024-03-17 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_task_created_by_name_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='s3_url',
            field=models.URLField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
